sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VU0HQVLrK3Zf+KeMCTz+A8iHKbT9pnbLJe8hOy0j1bAj2DPvaaaw+8Ci4dpSDwASjHK6iryBfbclCHyqQVblN1OF38BbD2425BfoZrGU5xGkjCwm2yAo6sIIxmWX5s1tSleoMLZ2h0D74E4Kx/pMut9gwIuzKA9KCq14bts0TtaimhjeHfVpw4ZwvZtuMYO3JZctJzhGcFSjDA4N1rMCT5CPK0ofwgrz/fUfmUiOX62GDoxZ7nfmGTD36JFrLW/irtM+/h46iBRouMhcgGL/xGoLwhcQvARBGeV7Ik+stPQJfXryRbT+7Jc+cz/IyYXdFO2FdtHh/GDOXmq29T0xgTSt/aE8v9VwwsvT0Ll5qdUkRlVIH/jHGGwsSX7G8Jx28PirEnjzCNEcwzY05CYNeeJXDpnjpKOLmpQYvnpNPZCCp5Av6IsqgtMKCDsDgg8yKTDWrMWVzFkN8o9rVGo1tZ9CoGIsGgIaMsl41v72dk5VzzsgDyesG6sv9dmNR6cbno9ySghadnizxBluCl0R9KzOrfGszigfRVayEihhV91OOfxGtAO4Mgu3sVMjfXlYr+pAsnSekhv+VZlGzf8mMFiHQiRfqa1RMx9hNG9bWaAPeuJNhRgFfCFrQ5CNpPRIhJkiub0N8sctpuVDxaQZvB2yvuzeUfh+mpO8/5YE6TI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/A-Start-in-Life_1403
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy